### ISSUE TITLE
Login Succeed via panga jailbreak. 

### ISSUE THREAD

**Issue by Co2333** [AppleBetas/MTerminal-Jailed#1]
![29b0b1ef-193b-4e89-9794-22cbe0d76771](https://user-images.githubusercontent.com/25259084/34327390-0752b458-e8fe-11e7-8ce3-006e2d303fa3.png)
iOS 11.1.2

**Comment by AppleBetas** [comment]
Not sure what this issue is trying to say. If its that login works with this jailbreak, there are a few other issues holding it back from working here. Closed.
