### ISSUE TITLE
Bad CPU type in executable. 

### ISSUE THREAD

**Issue by Co2333** [AppleBetas/MTerminal-Jailed#3]
![4c396ec3-41a6-4432-9146-f274a472a4fe](https://user-images.githubusercontent.com/25259084/34329605-0229e84a-e942-11e7-9317-b887031977c5.png)

**Comment by AppleBetas** [comment]
Caused by other jailbreak tool installing over /bootstrap with incorrect binaries. You can try deleting the bootstrap folder and re-running MTerminal-Jailed, but it may not work. Closed.
